### ISSUE TITLE
Switch to OFL

### ISSUE THREAD

**Issue by davelab6** [dbenjaminmiller/regis#1]
The OFL isn't compatible with "any other license", and creates a commons which this font isn't part of. Would you consider switching? :)

**Comment by dbenjaminmiller** [comment]
Sorry for this being so late: the OFL isn't, but other licenses can be compatible with the OFL (i.e., this font isn't OFL-licensed, but a deriv. can be). Actually my intention here was to be essentially public domain. But in any case this font isn't really useful. It's far too sloppy. I'd have to start over now. And I hope to do so at some point when I have time.
